### ISSUE TITLE
Nextcloud: Default language

### ISSUE THREAD

**Issue by cstuder** [oberfeld/oberdocker#5]
https://docs.nextcloud.com/server/15/admin_manual/configuration_server/language_configuration.html

Auf `de` oder so stellen.

(Ist gerade zu spät um es schnell schnell zu machen...)

**Comment by cstuder** [comment]
https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/config_sample_php_parameters.html?highlight=language#user-experience

**Comment by avecunk** [comment]
Per occ hinzugefügt: Hier die Beschreibung https://github.com/oberfeld/oberdocker#configuration. Keine definitive Lösung (à la env File)

**Comment by avecunk** [comment]
see https://github.com/oberfeld/oberdocker/issues/5#issuecomment-849443095
